/* Mac-only copy; the public Web app and its translations stay untouched. */
window.TAWEL_MAC_COPY = {
 de: {
  performance:'Leistung', cameraQuality:'Analysebild', standardQuality:'Standard · bis 640 × 480', detailQuality:'Detail · bis 1280 × 720', fingerFallback:'Verdeckte Fingerspitzen ergänzen', qualityNote:'Das Analysebild wird auf diese Größe begrenzt, ohne Beschnitt. Ein Wechsel startet dieselbe Kamera kurz neu. Ersatzpunkte helfen bei verdeckten Spitzen.', actualResolution:'Tatsächliches Analysebild', analysisRate:'Analysen pro Sekunde', analysisTime:'Letzte Analyse', cpuLoad:'CPU · Tawel-Prozess', thermal:'Thermischer Zustand', thermalStates:['Normal','Leicht erhöht','Hoch','Sehr hoch'], performanceNote:'100 % CPU entspricht einem Kern; WebKit und GPU sind nicht enthalten. Das CSV ergänzt Speicher- und Tonmesswerte, keine Bilder.',

  animation:'Animation', blurAnimation:'Unschärfe abstimmen', blurAmount:'Unschärfe', fadeIn:'Einblenden', fadeOut:'Ausblenden', resetAnimation:'Zurücksetzen', animationNote:'Der Hinweis ist ein kurzer Impuls wie der Ton: Er blendet weich ein, bleibt etwa eine Sekunde und blendet wieder aus – auch wenn die Hand noch im Bereich ist. Die Vorschau zeigt genau diesen Ablauf. Unschärfe gilt für Fokusverlust und Farbhauch → Fokusverlust. Bei „Bewegung reduzieren“ werden die Übergänge verkürzt.',
  focus: 'Fokus', settings: 'Einstellungen', camera: 'Kamera', change: 'Ändern', cue: 'Visueller Hinweis', break: 'Pause für', selectBreak: 'Dauer wählen', background: 'Im Hintergrund weiterlaufen', backgroundNote: 'Fenster schließen? Tawel bleibt aktiv. Über den Ring in der Menüleiste kommst du jederzeit zurück.',
  makeItYours: 'So, wie es für dich passt.', settingsIntro: 'Ein ruhiger Hinweis. In deiner Stärke.', style: 'Darstellung', intensity: 'Stärke', light: 'Leicht', medium: 'Mittel', strong: 'Deutlich', preview: 'Vorschau', heldNote: 'Bleibt sichtbar, solange die Hand am Mund erkannt wird. Die Vorschau dauert nur kurz.', detection: 'Erkennung', sensitivity: 'Empfindlichkeit', later: 'Später', balanced: 'Ausgewogen', earlier: 'Früher', sensitivityNote: '„Früher“ reagiert schon bei etwas größerem Abstand zum Mund.', cameraNote: 'Bei mehreren Kameras entscheidest du. Kein stiller Wechsel auf eine andere Kamera.', privacy: 'Lokal auf deinem Mac · Keine Bildaufnahme',
  ready: 'Bereit', active: 'Aktiv', paused: 'Pausiert', waiting: 'Startet …', attention: 'Kamera prüfen', choose: 'Kamera wählen …',
  readyTitle: 'Ein ruhiger Begleiter.', readyText: 'Wähle deine Kamera. Tawel hilft dir, Hand-zum-Mund-Bewegungen früher zu bemerken.', activeTitle: 'Du kannst einfach weitermachen.', activeText: 'Tawel ist aufmerksam – auch bei geschlossenem Fenster.', cueTitle: 'Ein Moment für dich.', cueText: 'Der Hinweis klingt ab, sobald du die Hand vom Mund nimmst.', pausedTitle: 'Zeit für eine Pause.', pausedText: 'Die Kamera ist aus. Mach weiter, wenn du bereit bist.', snoozeText: 'Die Erkennung startet wieder um', waitingTitle: 'Einen Augenblick.', waitingText: 'Die Kamera startet. Die Erkennung braucht einige Sekunden.', chooseText: 'Wähle im Kamerafenster die Kamera, die du verwenden möchtest.', deniedTitle: 'Kamerazugriff erlauben.', deniedText: 'Erlaube Tawel den Kamerazugriff in Systemeinstellungen → Datenschutz & Sicherheit → Kamera.', unavailableTitle: 'Kamera nicht verfügbar.', unavailableText: 'Prüfe die Verbindung oder wähle eine andere Kamera.', errorTitle: 'Die Kamera konnte nicht starten.', errorText: 'Prüfe die Kamera und versuche es erneut.', sleepTitle: 'Tawel ruht.', sleepText: 'Nach dem Aufwachen setzt Tawel die Erkennung fort.', start: 'Kamera starten', pause: 'Pausieren', resume: 'Fortsetzen', retry: 'Kamera auswählen', noCamera: 'Noch keine Kamera gewählt', connectionError: 'Die Verbindung zu Tawel ist unterbrochen. Bitte öffne die App erneut.', actionError: 'Das hat nicht geklappt. Bitte versuche es erneut.',
  styles: {'lavender-vignette':'Lavendel-Vignette','soft-focus':'Sanfter Fokusverlust',desaturate:'Entsättigung','ambient-glow':'Ambient Glow','wash-focus':'Farbhauch & Fokusverlust'}
 },
 en: {
  performance:'Performance', cameraQuality:'Analysis image', standardQuality:'Standard · up to 640 × 480', detailQuality:'Detail · up to 1280 × 720', fingerFallback:'Use joints for hidden fingertips', qualityNote:'Analysis is limited to this size without cropping. Switching briefly restarts the same camera. Adjacent joints help when tips are hidden.', actualResolution:'Actual analysis image', analysisRate:'Analyses per second', analysisTime:'Last analysis', cpuLoad:'CPU · Tawel process', thermal:'Thermal state', thermalStates:['Normal','Fair','Serious','Critical'], performanceNote:'100% CPU is one core; excludes WebKit and GPU. The CSV adds memory and sound measurements, never images.',

  animation:'Animation', blurAnimation:'Tune the blur', blurAmount:'Blur', fadeIn:'Fade in', fadeOut:'Fade out', resetAnimation:'Reset', animationNote:'The cue is a short impulse like the sound: it fades in softly, stays for about a second and fades out again – even if your hand is still there. The preview shows exactly this. Blur applies to Soft focus and Colour wash → focus. Reduce Motion shortens the transitions.',
  focus: 'Focus', settings: 'Settings', camera: 'Camera', change: 'Change', cue: 'Visual cue', break: 'Pause for', selectBreak: 'Choose duration', background: 'Keep running in background', backgroundNote: 'Closing the window keeps Tawel running. Return anytime using the ring in your menu bar.',
  makeItYours: 'Make yourself comfortable.', settingsIntro: 'A quiet cue. At your own strength.', style: 'Appearance', intensity: 'Strength', light: 'Light', medium: 'Medium', strong: 'Noticeable', preview: 'Preview', heldNote: 'Stays visible while a hand is detected near your mouth. The preview is brief.', detection: 'Detection', sensitivity: 'Sensitivity', later: 'Later', balanced: 'Balanced', earlier: 'Earlier', sensitivityNote: '“Earlier” responds at a slightly greater distance from your mouth.', cameraNote: 'With multiple cameras, you choose. Tawel never silently switches to another camera.', privacy: 'On your Mac · No images recorded',
  ready: 'Ready', active: 'Active', paused: 'Paused', waiting: 'Starting …', attention: 'Check camera', choose: 'Choose camera …', readyTitle: 'A quiet companion.', readyText: 'Choose your camera. Tawel helps you notice hand-to-mouth movements sooner.', activeTitle: 'Carry on with your day.', activeText: 'Tawel stays attentive, even with this window closed.', cueTitle: 'A moment for yourself.', cueText: 'The cue fades when you move your hand away from your mouth.', pausedTitle: 'Time for a break.', pausedText: 'The camera is off. Continue when you are ready.', snoozeText: 'Detection resumes at', waitingTitle: 'Just a moment.', waitingText: 'Your camera is starting. Detection takes a few seconds.', chooseText: 'Select the camera you want to use in the camera dialog.', deniedTitle: 'Allow camera access.', deniedText: 'Allow Tawel to access your camera in System Settings → Privacy & Security → Camera.', unavailableTitle: 'Camera unavailable.', unavailableText: 'Check the connection or choose another camera.', errorTitle: 'The camera could not start.', errorText: 'Check your camera and try again.', sleepTitle: 'Tawel is resting.', sleepText: 'Detection will resume after your Mac wakes up.', start: 'Start camera', pause: 'Pause', resume: 'Resume', retry: 'Choose camera', noCamera: 'No camera selected yet', connectionError: 'The connection to Tawel was interrupted. Please reopen the app.', actionError: 'That did not work. Please try again.',
  styles: {'lavender-vignette':'Lavender vignette','soft-focus':'Gentle focus shift',desaturate:'Desaturation','ambient-glow':'Ambient glow','wash-focus':'Color wash & focus shift'}
 }
};

Object.assign(window.TAWEL_MAC_COPY.de, {
 review:'Rückblick', day:'Tag', daySummary:'Dein Tag in Kürze', observed:'Erkennungszeit', quietTime:'Längste ruhige Phase', dayCourse:'Momente im Tagesverlauf',
 reviewNote:'Nur Zeit mit verlässlicher Erkennung zählt. Pausen, fehlendes Gesicht und Trackingausfälle zählen nicht als ruhige Zeit. Daten bleiben auf diesem Mac.',
 noReview:'Für diesen Tag gibt es noch keine Erkennungszeit.', momentsText:'erkannte Momente', streakOne:'Tag mit mindestens 10 Minuten Erkennung und weniger als 5 Momenten.', streakText:'aufeinanderfolgende Tage mit mindestens 10 Minuten Erkennung und weniger als 5 Momenten.',
 sound:'Ton', soundEnabled:'Klang beim Hinweis', soundChoice:'Klang', volume:'Lautstärke', testSound:'Klang testen', soundNote:'Einmal pro Annäherung, auch bei geschlossenem Fenster.',
 sounds:['Bubble Pop','Doppel-Klopfen','Atem-Glocke','Mini-Roboter','Boing'],
 trackingTitle:'Gesicht ausrichten.', trackingText:'Der Mund ist gerade nicht sicher erkennbar. Prüfe Bildausschnitt und Licht.', handTrackingTitle:'Handpunkte unsicher.', handTrackingText:'Eine Hand ist sichtbar, ihre Fingerposition aber noch nicht eindeutig. Tawel prüft weiter.', analysisWaitingTitle:'Auswertung wartet.', analysisWaitingText:'Die Kameraauswertung liefert gerade kein aktuelles Ergebnis. Tawel versucht es weiter.',
 backgroundNote:'Fenster schließen oder minimieren: Eine laufende Erkennung bleibt aktiv. Öffnen über den Menüleistenring oder das Dock. Beenden mit ⌘Q.',
 heldNote:'Bleibt bei Handnähe sichtbar. Kurze Verdeckungen werden überbrückt; bei längerem Trackingverlust wird der Bildschirm freigegeben.'
});
Object.assign(window.TAWEL_MAC_COPY.en, {
 review:'Review', day:'Day', daySummary:'Your day at a glance', observed:'Detection time', quietTime:'Longest quiet stretch', dayCourse:'Moments throughout the day',
 reviewNote:'Only reliable detection time counts. Pauses, missing faces and tracking failures do not count as quiet time. Data stays on this Mac.',
 noReview:'No detection time for this day yet.', momentsText:'detected moments', streakOne:'day with at least 10 minutes of detection and fewer than 5 moments.', streakText:'consecutive days with at least 10 minutes of detection and fewer than 5 moments.',
 sound:'Sound', soundEnabled:'Play a sound with cues', soundChoice:'Sound', volume:'Volume', testSound:'Test sound', soundNote:'Once per approach, even with the window closed.',
 sounds:['Bubble Pop','Double Tap','Breath Bell','Tiny Robot','Boing'],
 trackingTitle:'Position your face.', trackingText:'Your mouth is not clearly visible. Check framing and light.', handTrackingTitle:'Hand points unclear.', handTrackingText:'A hand is visible, but finger positions are uncertain. Tawel keeps checking.', analysisWaitingTitle:'Waiting for analysis.', analysisWaitingText:'Camera analysis is not providing a current result. Tawel keeps trying.',
 backgroundNote:'Closing or minimizing keeps an active session running. Reopen from the menu bar ring or Dock. Quit with ⌘Q.',
 heldNote:'Stays visible near your mouth. Brief occlusions are tolerated; prolonged tracking loss releases the screen.'
});

Object.assign(window.TAWEL_MAC_COPY.de, {
 imageSound:'Bild & Ton', settingsIntro:'Erkennung, Hinweise und Kamera. Alles an seinem Platz.', intensity:'Hinweisstärke',
 detectionTitle:'Wann möchtest du erinnert werden?', detectionExplanation:'Die Empfindlichkeit bestimmt den Abstand zwischen Hand und Mund. Wie deutlich der Hinweis aussieht oder klingt, stellst du unter „Bild & Ton“ ein.',
 nativeCue:'Nativ zeichnen (Test)', nativeCueNote:'Vom System animiert statt im App-Fenster: gleiche Dauer und Kurve bei jedem Durchlauf. Stil, Stärke und Zeiten gelten für beide Wege.', cameraPreview:'Kamerabild mit Erkennung zeigen', previewOff:'Die Vorschau ist ausgeblendet.', previewWaiting:'Starte die Kamera oder setze die Erkennung fort. Das Livebild erscheint nach dem Anlaufen.',
 previewNote:'Gespiegeltes Livebild · Punkte und Linien aus der laufenden Erkennung. Nur hier sichtbar, keine Bilder gespeichert.',
 privacy:'Lokal auf deinem Mac · Keine Bilder gespeichert'
});
Object.assign(window.TAWEL_MAC_COPY.en, {
 imageSound:'Visuals & sound', settingsIntro:'Detection, cues and camera. Each in its place.', intensity:'Cue strength',
 detectionTitle:'When would you like a reminder?', detectionExplanation:'Sensitivity controls the distance between your hand and mouth. Adjust how the cue looks or sounds under “Visuals & sound”.',
 nativeCue:'Native rendering (test)', nativeCueNote:'Animated by the system instead of inside the app window: same duration and curve on every run. Style, intensity and timings apply to both.', cameraPreview:'Show camera with detection', previewOff:'The preview is hidden.', previewWaiting:'Start your camera or resume detection. The live view appears after startup.',
 previewNote:'Mirrored live view · Points and lines from active detection. Visible only here; no images saved.', privacy:'On your Mac · No images saved'
});
